### ISSUE TITLE
Do you knoe our jazz-community on GIThub?

### ISSUE THREAD

**Issue by schneigu** [jeromede/rtc.pa#1]
Hello,

Do you know our Jazz-Community here on GIThub? Maybe you bring your ptoject into the community like for example Ralph did with his workitem command line tool.

Cheers
Guido Schneider

**Comment by jeromede** [comment]
Hello, how does this work? J.

**Comment by schneigu** [comment]
@innerjoin 
Lukas, may you support @jeromede the transfer into the community and explain how to work?
